export const BREADS = [
  {
    id: 1,
    name: "Old-fashioned Rustic White Bread",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, rice flour, olive oil, baking powder, brown sugar, xanthan gum, yeast, salt, vinegar, enzymes",
    type: "bread",
    img: "b_white.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 2,
    name: "Multigrain Bread",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, brown rice flour, brown sugar, olive oil, molasses, baking powder, xanthan gum, yeast, sea salt, vinegar, poppy seeds, sunflower seeds, flaxseeds, sesame seeds, enzymes",
    type: "bread",
    img: "b_multigrain.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 3,
    name: "Rosemary Olive Bread",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, corn starch, potato starch, tapioca starch, olives, egg whites, rice flour, olive oil, baking powder, brown sugar, xanthan gum, yeast, salt, vinegar, rosemary, enzymes",
    type: "bread",
    img: "b_olive.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 4,
    name: "Apple Cinnamon Raisin Bread",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, rice flour, raisins, brown sugar, canola oil, apples, molasses, baking powder, cinnamon, xanthan gum, yeast, salt, vinegar, enzymes",
    type: "bread",
    img: "b_rasin.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 5,
    name: "Mozzarella Basil Garlic Bread",
    info: "gluten-free, soy-free, and nut-free; contains eggs and dairy",
    ingredients: "water, corn starch, potato starch, tapioca starch, egg whites, rice flour, mozzarella cheese, cheddar cheese, provolone cheese, olive oil, baking powder, brown sugar, xanthan gum, yeast, salt, vinegar, basil, garlic, enzymes",
    type: "bread",
    img: "b_mozarella.jpg",
    dairy: true,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },

];

export const BAGELS = [
  {
    id: 6,
    name: "Plain Bagel",
    info: "gluten-free, soy-free, dairy-free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, rice flour, olive oil, baking powder, brown sugar, xanthan gum, yeast, sea salt, vinegar, enzymes",
    type: "bagel",
    img: "bagel_plain.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 7,
    name: "Cinnamon Raisin Bagel",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, rice flour, raisins, brown sugar, canola oil, apples, molasses, baking powder, cinnamon, xanthan gum, yeast, salt, vinegar, enzymes",
    type: "bagel",
    img: "bagel_rasin_cinnamon.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 8,
    name: "Sesame Bagel",
    info: "gluten-free, soy-free, dairy free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, rice flour, olive oil, baking powder, brown sugar, xanthan gum, yeast, salt, vinegar, sesame, enzymes",
    type: "bagel",
    img: "bagel_sesame_true.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 9,
    name: "Multigrain Bagel",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, brown rice flour, brown sugar, olive oil, molasses, baking powder, xanthan gum, yeast, salt, vinegar, poppy seeds, sunflower seeds, flaxseeds, sesame seeds, enzymes",
    type: "bagel",
    img: "bagel_multigrain.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 10,
    name: "Everything Bagel",
    info: "gluten-free, soy-free, dairy free, and nut-free; contains eggs",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, butter milk, rice flour, olive oil, baking powder, brown sugar, xanthan gum, yeast, vinegar, sesame, poppy seed, onion, garlic, caraway, salt, enzymes",
    type: "bagel",
    img: "bagel_everything.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  }
];

export const PASTRIES = [
  {
    id: 11,
    name: "Cranberry Orange Muffin",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, cranberries, canola oil, whole eggs, cornstarch, tapioca flour, orange juice concentrate, baking powder, orange oil, salt, vanilla extract, enzymes",
    type: "muffin",
    img: "muffin_cran.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 12,
    name: "Wild Blueberry Muffin",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, blueberries, canola oil, whole eggs, cornstarch, tapioca flour, baking powder, salt, vanilla extract, enzymes",
    type: "muffin",
    img: "muffin_blue.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {

    id: 13,
    name: "Cinnamon Coffee Cake Muffin",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, canola oil, whole eggs, corn starch, tapioca starch, baking powder, cinnamon, brown sugar, maple flavor, salt, vanilla extract, enzymes",
    type: "muffin",
    img: "muffin_coffee.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {

    id: 14,
    name: "English Muffin",
    info: "gluten-free, soy-free, and nut-free; contains eggs and dairy",
    ingredients: "water, cornstarch, potato starch, tapioca starch, egg whites, rice flour, olive oil, baking powder, brown sugar, xanthan gum, yeast, sea salt, apple cider vinegar, enzymes",
    type: "bread",
    img: "muffin_eng.jpg",
    dairy: true,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {

    id: 15,
    name: "Classic Fudge Brownie",
    info: "gluten-free, and nut-free; contains eggs and dairy, may contain soy",
    ingredients: "chocolate chips, sugar, whole eggs, butter, cornstarch, rice flour, salt, vanilla extract, cocoa butter, cocoa powder, soy lecithin, enzymes",
    type: "pastry",
    img: "fudge_classic.jpg",
    dairy: true,
    soy: true,
    nut: false,
    egg: true,
    vegan: false
  },
  {

    id: 16,
    name: "Raspberry Cream Swirl Brownie",
    info: "gluten-free, and nut-free; contains eggs and dairy, may contain soy",
    ingredients: "chocolate chips, sugar, whole eggs, butter, cornstarch, rice flour, raspberry preserves, cream cheese, vanilla extract, salt, cocoa butter, cocoa powder, soy lecithin, enzymes",
    type: "pastry",
    img: "swirl.jpg",
    dairy: true,
    soy: true,
    nut: false,
    egg: true,
    vegan: false
  },
  {

    id: 17,
    name: "Chocolate Chip Cookies",
    info: "gluten-free, and nut-free; contains eggs and dairy, may contain soy",
    ingredients: "potato starch, brown sugar, butter, chocolate chips, rice flour, whole egg, cocoa powder, cocoa butter, baking powder, soy lecithin, salt, vanilla extract, enzymes",
    type: "pastry",
    img: "c1.jpg",
    dairy: true,
    soy: true,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 18,
    name: "Raisin Cranberry Cookies",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "brown sugar, canola oil, raisins, cranberries, cornstarch, rice flour, egg whites, coconut flakes, molasses, cinnamon, baking powder, xanthan gum, salt, vanilla extract, enzymes",
    type: "pastry",
    img: "c2_2.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 19,
    name: "Vanilla Cupcake",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, canola oil, coco powder, palm oil, whole eggs, cornstarch, tapioca flour, baking powder, xanthan gum, salt, vinegar, vanilla extract, enzymes",
    type: "pastry",
    img: "vanilaCupcake.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 20,
    name: "Chocolate Cupcake",
    info: "gluten-free, dairy-free, and nut-free; contains eggs, may contain soy",
    ingredients: "water, sugar, rice flour, canola oil, coco powder, palm oil, whole eggs, cornstarch, tapioca flour, baking powder, xanthan gum, salt, vinegar, vanilla extract, enzymes",
    type: "pastry",
    img: "chocolateCupcake.jpg",
    dairy: false,
    soy: true,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 21,
    name: "Whoopie Pie",
    info: "gluten-free, dairy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, canola oil, coco powder, palm oil, whole eggs, cornstarch, tapioca flour, baking powder, xanthan gum, salt, vinegar, vanilla extract, enzymes",
    type: "pastry",
    img: "WhooThumb.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 22,
    name: "Red Velvet Whoopie Pie",
    info: "gluten-free, and nut-free; contains eggs and dairy",
    ingredients: "water, sugar, rice flour, canola oil, coco powder, palm oil, butter, butter milk, whole eggs, cornstarch, tapioca flour, baking powder, cinnamon, xanthan gum, salt, vinegar, vanilla extract, natural food color, enzymes",
    type: "pastry",
    img: "whoopieRedVelvet.jpg",
    dairy: true,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 23,
    name: "Coconut Macaroon",
    info: "gluten-free, soy-free, and nut-free; contains eggs",
    ingredients: "coconut flakes, sugar, egg whites, vanilla extract",
    type: "pastry",
    img: "macaroon.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 24,
    name: "Raspberry Crisp Square",
    info: "gluten-free, dairy-free, soy-free, egg free, and nut-free",
    ingredients: "rice flour, potato starch, tapioca starch, raspberries, brown sugar, palm oil, canola oil, lemon juice, baking powder, xanthan gum, salt, cinnamon, vanilla",
    type: "pastry",
    img: "square1.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: false,
    vegan: true
  },
  {
    id: 25,
    name: "Blueberry Square",
    info: "gluten-free, dairy-free, soy-free, egg free, and nut-free",
    ingredients: "rice flour, potato starch, tapioca starch, blueberries, brown sugar, palm oil, canola oil, lemon juice, baking powder, xanthan gum, salt, cinnamon, vanilla",
    type: "pastry",
    img: "square2.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: false,
    vegan: true
  },
  {
    id: 26,
    name: "Cherry Crisp Square",
    info: "Gluten-Free, Dairy-Free, Soy-Free, Egg Free, And Nut-Free",
    ingredients: "rice flour, potato starch, tapioca starch, cherries, brown sugar, palm oil, canola oil, lemon juice, baking powder, xanthan gum, salt, cinnamon, vanilla",
    type: "pastry",
    img: "square2.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: false,
    vegan: true
  },
  {
    id: 27,
    name: "Apple Crisp Square",
    info: "Gluten-Free, Dairy-Free, Soy-Free, Egg Free, And Nut-Free",
    ingredients: "rice flour, potato starch, tapioca starch, brown sugar, apples, palm oil, canola oil, lemon juice, baking powder, xanthan gum, salt, cinnamon, vanilla",
    type: "pastry",
    img: "apple_bar.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: false,
    vegan: true
  },
  {
    id: 28,
    name: "Wild Blueberry Tea Bread",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, blueberries, canola oil, whole eggs, cornstarch, tapioca flour, baking powder, salt, vanilla extract, enzymes",
    type: "pastry",
    img: "wildblueberryTeaBread.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 29,
    name: "Cranberry Orange Tea Bread",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, cranberries, canola oil, whole eggs, cornstarch, tapioca flour, orange juice concentrate, baking powder, orange oil, salt, vanilla extract, enzymes",
    type: "pastry",
    img: "cranberryOrangeTeaBread.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  },
  {
    id: 30,
    name: "Cinnamon Coffee Cake Tea Bread",
    info: "gluten-free, dairy-free, soy-free, and nut-free; contains eggs",
    ingredients: "water, sugar, rice flour, canola oil, whole eggs, cornstarch, tapioca flour, baking powder, cinnamon, brown sugar, maple flavor, salt, vanilla extract, enzymes",
    type: "pastry",
    img: "coffeeCinnamonTeaBread.jpg",
    dairy: false,
    soy: false,
    nut: false,
    egg: true,
    vegan: false
  }
];
